CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_MANUFACTURER="Seeed Studio"
CONFIG_USB_DEVICE_PRODUCT="SlimeNRF Tracker XIAO"
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y
CONFIG_BOOT_DELAY=2000

CONFIG_BATTERY_USE_REG_LDO_MAPPING=y
CONFIG_LED_RGB_COLOR=y
